language: node_js
node_js:
  - "8"
branches:
  except:
    - gh-pages
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm
    cd -
  } || true
env: PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
    - "node_modules"
    - ~/.npm 
    - ~/npm
before_script: npm install -g npm@5.10.0
jobs:
  include:
    - stage: update-lockfile
      if: branch = /^greenkeeper\/.*$
      before_install:
        - npm install -g greenkeeper-lockfile
      install: npm install
      before_script: greenkeeper-lockfile-update
      script: greenkeeper-lockfile-upload
    - stage: lint
      install: npm ci
      script: npm run tslint
    - stage: test
      before_install: npm i -g codecov
      install: npm ci
      script: npm test
      after_script: codecov
    - stage: build
      install: npm ci
      script: npm run build
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        fqdn: francesco-agnoletto.com
        on:
          branch: master
