language: node_js
node_js:
  - "8"
branches:
  except:
    - gh-pages
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g greenkeeper-lockfile@2 codecov now

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run type-check
  - npm run tslint
  - npm run test--ci
  - npm run build

after_script:
  - codecov
  - greenkeeper-lockfile-upload

deploy:
  provider: script
  script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN && now rm personal-website --safe --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true
